name: Buf Generate
description: Generate new schema changes from BSR
author: Tim Kotowski

inputs:
  user:
    required: true
    description: "Owner of Buf Schema Registry"
  token:
    required: true
    description: "Token for accessing Buf Schema API"

runs:
  using: composite
  steps:
    - name: Buf Checkout
      id: buf-checkout
      uses: bufbuild/buf-action@v1
      with:
        token: ${{ inputs.token }}
        setup_only: true

    - name: Buf Login
      run: buf registry login --username ${{ secrets.BUF_USER }} --token ${{ secrets.BUF_TOKEN }}
      shell: bash

    - name: Buf Generate
      id: buf_generate
      run: buf generate
      shell: bash