name: Buf Generate
description: Generate new schema changes from BSR
author: Tim Kotowski

inputs:
  token:
    required: true
    description: "Token for accessing Buf Schema API"

runs:
  using: composite
  steps:
    - name: Buf Checkout
      id: buf-checkout
      uses: bufbuild/buf-action@v1
      with:
        token: ${{ inputs.token }}
        setup_only: true

#    - name: Buf Login
#      run: echo BUF_TOKEN=${{ inputs.token }} | buf registry login --token-stdin
#      shell: bash

    - name: Buf Generate
      id: buf_generate
      run: buf generate
      shell: bash